--DROP TABLE IF EXISTS MARKET_TRADES;

CREATE TABLE IF NOT EXISTS MARKET_TRADES
(
    THE_TIME         TIMESTAMPTZ,
    MARKET           VARCHAR,
    PRICE            DOUBLE,
    SIZE             DOUBLE,
    SIDE             VARCHAR,
    OUTCOME          VARCHAR,
    PRICE_TO_BEAT    DOUBLE,
    FINAL_PRICE      DOUBLE,
    RESULT           VARCHAR,
    VOLUME           DOUBLE,
    N_TRADES         INTEGER,
    SECS_INTO_WINDOW INTEGER,
    EVENT_OPEN       TIMESTAMPTZ,
    EVENT_START      TIMESTAMPTZ,
    EVENT_CLOSE      TIMESTAMPTZ,
    WALLET           VARCHAR,
    USER_NAME        VARCHAR,
    USER_PSUEDO      VARCHAR
);
