INSERT INTO MARKET_TRADES

WITH _MARKET_TRADES AS (
    SELECT SlUG AS MARKET,
    TIMESTAMP AS THE_TIME,
    SECS_INTO_WINDOW,
    SIDE,OUTCOME,
    PRICE,
    SIZE,
    WALLET,NAME AS USER_NAME,PSEUDONYM AS USER_PSUEDO
    FROM btc_trades
),
MARKETS_SUMMARY AS (
SELECT
    SlUG AS MARKET,
    MARKET_ID,
    EVENT_STARTTIME AS EVENT_START,
    EVENT_END_DATE AS EVENT_CLOSE,
    PRICE_TO_BEAT,
    FINAL_PRICE,
    RESULT,VOLUME,
    N_TRADES,
    EVENT_START_DATE AS EVENT_OPEN
    FROM btc_summary

),
MARKET_TRADES AS(
SELECT
    t.THE_TIME,t.MARKET,
    -- Trade info
    t.PRICE,t.SIZE,t.SIDE,t.OUTCOME,

    -- Market stats
    s.PRICE_TO_BEAT,s.FINAL_PRICE,s.RESULT,
    s.VOLUME,s.N_TRADES,
    t.secs_into_window,
    s.EVENT_OPEN,s.EVENT_START,s.EVENT_CLOSE,
    -- Trader info
    t.WALLET,t.USER_NAME,t.USER_PSUEDO
FROM _MARKET_TRADES t
JOIN MARKETS_SUMMARY s on s.MARKET = t.MARKET
ORDER BY MARKET,THE_TIME ASC
)

SELECT *
FROM MARKET_TRADES;