
DROP VIEW IF EXISTS market_trades_v;

CREATE OR REPLACE VIEW market_trades_v AS
SELECT
    TIMESTAMP AS THE_TIME,
    EVENT_SLUG AS MARKET,
    Name,PSEUDONYM,PROXY_WALLET,
    PRICE,SIZE,
    ASSET,SIDE,OUTCOME,
    TRANSACTION_HASH
FROM bitcoin_5m_trades
ORDER BY PROXY_WALLET DESC;


