DROP TABLE IF EXISTS DIM_MARKET;
CREATE TABLE IF NOT EXISTS DIM_MARKET
(
    MARKET_ID        VARCHAR,
    dt_ID            VARCHAR,
    EVENT_SLUG       VARCHAR,
    EVENT_START_TIME TIMESTAMPTZ,
    END_DATE         TIMESTAMPTZ,
    RESULT           VARCHAR
);
